export const data = [
  {
    genre: "Computer Science",
    subGenres: [
      {
        name: "Programming Languages",
        subSubGenres: [
          "Python",
          "Java",
          "C++",
          "JavaScript",
          "C#",
          "Ruby",
          "Go",
          "Swift",
          "Kotlin",
          "PHP",
          "Perl",
          "R",
          "Objective-C",
          "Scala",
          "Haskell",
          "TypeScript",
          "Lua",
          "MATLAB",
          "Fortran",
          "COBOL",
          "Assembly",
          "Rust",
          "Elixir",
          "Erlang",
          "Dart",
          "F#",
          "Groovy",
          "VHDL",
          "Verilog",
          "Ada",
        ],
      },
      {
        name: "Software Engineering",
        subSubGenres: [
          "Agile Development",
          "DevOps",
          "Continuous Integration",
          "Software Testing",
          "Software Design",
          "Software Architecture",
          "Requirements Engineering",
          "Software Maintenance",
          "Quality Assurance",
          "Configuration Management",
          "Software Metrics",
          "Project Management",
          "Risk Management",
          "Software Process Improvement",
          "Formal Methods",
          "Model-Driven Engineering",
          "Reverse Engineering",
          "Refactoring",
          "Code Review",
          "Pair Programming",
        ],
      },
      {
        name: "Data Science",
        subSubGenres: [
          "Data Analysis",
          "Machine Learning",
          "Big Data",
          "Data Mining",
          "Statistical Analysis",
          "Data Visualization",
          "Predictive Analytics",
          "Data Engineering",
          "Natural Language Processing",
          "Time Series Analysis",
          "Deep Learning",
          "Artificial Intelligence",
          "Data Cleaning",
          "Data Warehousing",
          "Business Intelligence",
          "Data Governance",
          "Data Ethics",
          "Data Privacy",
          "Feature Engineering",
          "Model Evaluation",
        ],
      },
      {
        name: "Computer Networks",
        subSubGenres: [
          "Network Protocols",
          "Network Security",
          "Wireless Networks",
          "Internet of Things (IoT)",
          "Network Architecture",
          "Network Management",
          "Network Performance",
          "Cloud Computing",
          "Distributed Systems",
          "Peer-to-Peer Networks",
          "Network Simulation",
          "Network Forensics",
          "VPN",
          "SDN (Software-Defined Networking)",
          "Network Topology",
          "Network Troubleshooting",
          "LAN/WAN",
          "Network Virtualization",
          "Network Congestion",
          "Network Latency",
        ],
      },
      {
        name: "Databases",
        subSubGenres: [
          "Relational Databases",
          "NoSQL Databases",
          "Database Design",
          "Database Administration",
          "SQL",
          "Database Security",
          "Database Optimization",
          "Data Modeling",
          "Data Integrity",
          "Transaction Management",
          "Database Indexing",
          "Distributed Databases",
          "In-Memory Databases",
          "Cloud Databases",
          "Database Replication",
          "Database Backup and Recovery",
          "Database Migration",
          "Graph Databases",
          "Database Scalability",
          "Data Warehousing",
        ],
      },
    ],
  },
  {
    genre: "Economics & Finance",
    subGenres: [
      {
        name: "Microeconomics",
        subSubGenres: [
          "Consumer Behavior",
          "Production Theory",
          "Cost Analysis",
          "Market Structures",
          "Game Theory",
          "Behavioral Economics",
          "Health Economics",
          "Labor Economics",
          "Industrial Organization",
          "Public Economics",
          "Information Economics",
          "Welfare Economics",
          "Economics of Education",
          "Environmental Economics",
          "Urban Economics",
          "Regional Economics",
          "Experimental Economics",
          "Network Economics",
          "Resource Economics",
          "Development Economics",
        ],
      },
      {
        name: "Macroeconomics",
        subSubGenres: [
          "National Income",
          "Economic Growth",
          "Business Cycles",
          "Monetary Policy",
          "Fiscal Policy",
          "International Economics",
          "Development Economics",
          "Environmental Economics",
          "Regional Economics",
          "Urban Economics",
          "Political Economy",
          "Institutional Economics",
          "Open Economy Macroeconomics",
          "Macroeconomic Stabilization",
          "Inflation",
          "Unemployment",
          "Exchange Rates",
          "Macroeconomic Models",
          "Public Debt",
          "Macroeconomic Indicators",
        ],
      },
      {
        name: "Finance",
        subSubGenres: [
          "Corporate Finance",
          "Investment Banking",
          "Financial Markets",
          "Derivatives",
          "Portfolio Management",
          "Risk Management",
          "Behavioral Finance",
          "Quantitative Finance",
          "Real Estate Finance",
          "Public Finance",
          "International Finance",
          "Financial Econometrics",
          "Personal Finance",
          "Insurance",
          "Banking",
          "FinTech",
          "Financial Planning",
          "Hedge Funds",
          "Private Equity",
          "Venture Capital",
        ],
      },
      {
        name: "Accounting",
        subSubGenres: [
          "Financial Accounting",
          "Managerial Accounting",
          "Auditing",
          "Tax Accounting",
          "Forensic Accounting",
          "Governmental Accounting",
          "International Accounting",
          "Cost Accounting",
          "Environmental Accounting",
          "Accounting Information Systems",
          "Ethics in Accounting",
          "Budgeting",
          "Corporate Governance",
          "Nonprofit Accounting",
          "Accounting Theory",
          "Financial Reporting",
          "Accounting Standards",
          "Accounting Regulations",
          "Accounting Analytics",
          "Accounting for Mergers and Acquisitions",
        ],
      },
    ],
  },
  {
    genre: "Business & Management",
    subGenres: [
      {
        name: "Strategic Management",
        subSubGenres: [
          "Competitive Strategy",
          "Corporate Strategy",
          "Business Models",
          "Strategic Planning",
          "SWOT Analysis",
          "PEST Analysis",
          "Balanced Scorecard",
          "Core Competencies",
          "Resource-Based View",
          "Blue Ocean Strategy",
          "Strategic Innovation",
          "Strategic Alliances",
          "Mergers and Acquisitions",
          "Corporate Governance",
          "Global Strategy",
          "Strategy Implementation",
          "Strategy Execution",
          "Strategic Leadership",
          "Scenario Planning",
          "Strategic Decision Making",
        ],
      },
      {
        name: "Human Resource Management",
        subSubGenres: [
          "Recruitment",
          "Selection",
          "Training and Development",
          "Performance Management",
          "Compensation and Benefits",
          "Employee Relations",
          "Labor Law",
          "Organizational Behavior",
          "Diversity and Inclusion",
          "Talent Management",
          "HR Analytics",
          "Workforce Planning",
          "Employee Engagement",
          "Career Development",
          "Succession Planning",
          "Health and Safety",
          "HR Information Systems",
          "HR Strategy",
          "Employee Retention",
          "Change Management",
        ],
      },
      {
        name: "Operations Management",
        subSubGenres: [
          "Supply Chain Management",
          "Production Planning",
          "Inventory Management",
          "Quality Management",
          "Lean Manufacturing",
          "Six Sigma",
          "Operations Strategy",
          "Logistics Management",
          "Process Improvement",
          "Project Management",
          "Service Operations",
          "Capacity Planning",
          "Operations Research",
          "Total Quality Management",
          "Operations Scheduling",
          "Operations Risk Management",
          "Operations Analytics",
          "Operational Efficiency",
          "Operations Metrics",
          "Sustainable Operations",
        ],
      },
      {
        name: "Marketing",
        subSubGenres: [
          "Marketing Strategy",
          "Digital Marketing",
          "Social Media Marketing",
          "Content Marketing",
          "Brand Management",
          "Consumer Behavior",
          "Market Research",
          "Product Management",
          "Pricing Strategies",
          "Advertising",
          "Sales Management",
          "Marketing Analytics",
          "Customer Relationship Management (CRM)",
          "Marketing Communications",
          "Global Marketing",
          "Marketing Ethics",
          "Marketing Automation",
          "Integrated Marketing",
          "Event Marketing",
          "Influencer Marketing",
        ],
      },
    ],
  },
  {
    genre: "Politics & Government",
    subGenres: [
      {
        name: "Political Theory",
        subSubGenres: [
          "Liberalism",
          "Conservatism",
          "Socialism",
          "Communism",
          "Fascism",
          "Anarchism",
          "Feminism",
          "Environmentalism",
          "Libertarianism",
          "Nationalism",
          "Multiculturalism",
          "Political Philosophy",
          "Democratic Theory",
          "Justice Theory",
          "Theories of Power",
          "Utopianism",
          "Postcolonial Theory",
          "Critical Theory",
          "Republicanism",
          "Neo-Marxism",
        ],
      },
      {
        name: "International Relations",
        subSubGenres: [
          "Realism",
          "Liberalism",
          "Constructivism",
          "Marxism",
          "International Political Economy",
          "Global Governance",
          "Diplomacy",
          "Conflict Resolution",
          "Security Studies",
          "International Law",
          "Foreign Policy",
          "Human Rights",
          "Globalization",
          "Regionalism",
          "International Organizations",
          "International Security",
          "International Ethics",
          "Peace Studies",
          "International Development",
          "International Environmental Politics",
        ],
      },
      {
        name: "Comparative Politics",
        subSubGenres: [
          "Regime Types",
          "Democratization",
          "Political Institutions",
          "Electoral Systems",
          "Political Parties",
          "Political Culture",
          "State Formation",
          "Authoritarianism",
          "Federalism",
          "Decentralization",
          "Social Movements",
          "Civil Society",
          "Identity Politics",
          "Public Policy",
          "Comparative Method",
          "Comparative Political Economy",
          "Comparative Public Administration",
          "Comparative Constitutionalism",
          "Comparative Political Behavior",
          "Comparative Social Policy",
        ],
      },
      {
        name: "Public Administration",
        subSubGenres: [
          "Bureaucracy",
          "Public Management",
          "Public Policy Analysis",
          "Governance",
          "Public Sector Reform",
          "E-Government",
          "Public Budgeting",
          "Public-Private Partnerships",
          "Regulatory Policy",
          "Public Service Ethics",
          "Policy Implementation",
          "Performance Management",
          "Public Sector Innovation",
          "Public Finance",
          "Human Resource Management in Public Sector",
          "Administrative Law",
          "Government Accountability",
          "Public Sector Leadership",
          "Public Sector Marketing",
          "Crisis Management in Public Sector",
        ],
      },
    ],
  },
  {
    genre: "Philosophy",
    subGenres: [
      {
        name: "Metaphysics",
        subSubGenres: [
          "Ontology",
          "Cosmology",
          "Free Will",
          "Identity and Change",
          "Space and Time",
          "Determinism",
          "Possibility",
          "Necessity",
          "Modality",
          "Substance",
          "Causality",
          "Realism",
          "Idealism",
          "Dualism",
          "Monism",
        ],
      },
      {
        name: "Epistemology",
        subSubGenres: [
          "Knowledge",
          "Belief",
          "Justification",
          "Skepticism",
          "Sources of Knowledge",
          "Perception",
          "Memory",
          "Testimony",
          "Rationalism",
          "Empiricism",
          "Pragmatism",
          "Internalism",
          "Externalism",
          "Epistemic Virtue",
        ],
      },
      {
        name: "Ethics",
        subSubGenres: [
          "Moral Philosophy",
          "Normative Ethics",
          "Meta-Ethics",
          "Applied Ethics",
          "Virtue Ethics",
          "Deontology",
          "Consequentialism",
          "Utilitarianism",
          "Moral Relativism",
          "Moral Absolutism",
          "Bioethics",
          "Business Ethics",
          "Environmental Ethics",
        ],
      },
      {
        name: "Logic",
        subSubGenres: [
          "Formal Logic",
          "Informal Logic",
          "Symbolic Logic",
          "Predicate Logic",
          "Modal Logic",
          "Mathematical Logic",
          "Philosophical Logic",
          "Logical Positivism",
          "Logical Fallacies",
          "Argumentation Theory",
          "Proof Theory",
          "Model Theory",
        ],
      },
      {
        name: "Aesthetics",
        subSubGenres: [
          "Philosophy of Art",
          "Beauty",
          "Taste",
          "Criticism",
          "Aesthetic Experience",
          "Aesthetic Value",
          "Artistic Representation",
          "Art and Morality",
          "Art and Emotion",
          "Art and Knowledge",
          "Aesthetic Judgment",
          "Art Theory",
        ],
      },
      {
        name: "Political Philosophy",
        subSubGenres: [
          "Social Contract",
          "Justice",
          "Rights",
          "Liberty",
          "Equality",
          "Political Authority",
          "Democracy",
          "Communitarianism",
          "Libertarianism",
          "Anarchism",
          "Feminism",
          "Multiculturalism",
          "Global Justice",
        ],
      },
      {
        name: "Philosophy of Mind",
        subSubGenres: [
          "Consciousness",
          "Intentionality",
          "Mental States",
          "Qualia",
          "Dualism",
          "Physicalism",
          "Functionalism",
          "Artificial Intelligence",
          "Personal Identity",
          "Mind-Body Problem",
          "Perception",
          "Emotions",
        ],
      },
      {
        name: "Philosophy of Science",
        subSubGenres: [
          "Scientific Method",
          "Explanation",
          "Prediction",
          "Theory Change",
          "Realism and Anti-Realism",
          "Scientific Revolutions",
          "Paradigm Shifts",
          "Scientific Models",
          "Laws of Nature",
          "Science and Society",
          "Philosophy of Physics",
          "Philosophy of Biology",
        ],
      },
      {
        name: "Philosophy of Language",
        subSubGenres: [
          "Meaning",
          "Reference",
          "Truth",
          "Speech Acts",
          "Pragmatics",
          "Syntax",
          "Semantics",
          "Language Acquisition",
          "Linguistic Relativity",
          "Philosophy of Linguistics",
          "Communication",
          "Contextualism",
        ],
      },
      {
        name: "Philosophy of Religion",
        subSubGenres: [
          "Existence of God",
          "Faith and Reason",
          "Problem of Evil",
          "Religious Experience",
          "Divine Attributes",
          "Theodicy",
          "Religious Pluralism",
          "Secularism",
          "Mysticism",
          "Theology",
          "Atheism",
          "Agnosticism",
        ],
      },
      {
        name: "Existentialism",
        subSubGenres: [
          "Absurdity",
          "Authenticity",
          "Freedom",
          "Anguish",
          "Despair",
          "Existential Crisis",
          "Death",
          "Nothingness",
          "Being",
          "Phenomenology",
          "Subjectivity",
          "Existential Psychology",
          "Existential Literature",
        ],
      },
      {
        name: "Phenomenology",
        subSubGenres: [
          "Intentionality",
          "Conscious Experience",
          "Lifeworld",
          "Embodiment",
          "Intersubjectivity",
          "Temporal Experience",
          "Eidetic Reduction",
          "Existential Phenomenology",
          "Hermeneutic Phenomenology",
          "Phenomenological Method",
        ],
      },
    ],
  },
  {
    genre: "History",
    subGenres: [
      {
        name: "Ancient History",
        subSubGenres: [
          "Ancient Egypt",
          "Mesopotamia",
          "Ancient Greece",
          "Ancient Rome",
          "Indus Valley Civilization",
          "Ancient China",
          "Ancient Mesoamerica",
          "Persian Empire",
          "Ancient Africa",
          "Ancient Near East",
          "Prehistory",
          "Archaeology",
          "Classical Antiquity",
          "Bronze Age",
          "Iron Age",
        ],
      },
      {
        name: "Medieval History",
        subSubGenres: [
          "Early Middle Ages",
          "High Middle Ages",
          "Late Middle Ages",
          "Byzantine Empire",
          "Feudalism",
          "Crusades",
          "Medieval Europe",
          "Islamic Golden Age",
          "Medieval Asia",
          "Viking Age",
          "Medieval Warfare",
          "Medieval Society",
          "Medieval Religion",
          "Gothic Architecture",
        ],
      },
      {
        name: "Renaissance History",
        subSubGenres: [
          "Renaissance Art",
          "Renaissance Literature",
          "Renaissance Science",
          "Humanism",
          "Italian Renaissance",
          "Northern Renaissance",
          "Renaissance Politics",
          "Renaissance Culture",
          "Renaissance Music",
          "Renaissance Philosophy",
          "Reformation",
          "Age of Exploration",
        ],
      },
      {
        name: "Early Modern History",
        subSubGenres: [
          "Enlightenment",
          "Scientific Revolution",
          "Age of Discovery",
          "Reformation",
          "Counter-Reformation",
          "Thirty Years' War",
          "English Civil War",
          "French Revolution",
          "American Revolution",
          "Industrial Revolution",
          "Early Modern Europe",
          "Early Modern Asia",
        ],
      },
      {
        name: "Modern History",
        subSubGenres: [
          "19th Century History",
          "20th Century History",
          "World War I",
          "World War II",
          "Cold War",
          "Decolonization",
          "Modern Europe",
          "Modern America",
          "Modern Asia",
          "Modern Africa",
          "Modern Middle East",
          "Technological Advancements",
          "Social Movements",
        ],
      },
      {
        name: "Military History",
        subSubGenres: [
          "Ancient Military History",
          "Medieval Military History",
          "Early Modern Military History",
          "Modern Military History",
          "Military Strategies",
          "Famous Battles",
          "Military Leaders",
          "Military Technology",
          "Warfare Tactics",
          "Military Conflicts",
          "War Ethics",
        ],
      },
      {
        name: "Social History",
        subSubGenres: [
          "Gender History",
          "Labor History",
          "Social Movements",
          "Cultural History",
          "History of Education",
          "History of Medicine",
          "History of Family",
          "Urban History",
          "Rural History",
          "History of Childhood",
          "History of Disability",
          "Everyday Life in History",
        ],
      },
      {
        name: "Economic History",
        subSubGenres: [
          "History of Capitalism",
          "History of Socialism",
          "Industrial Revolution",
          "Economic Systems",
          "Trade History",
          "Financial History",
          "History of Agriculture",
          "History of Industry",
          "History of Technology",
          "Labor History",
          "Business History",
          "History of Globalization",
        ],
      },
      {
        name: "Cultural History",
        subSubGenres: [
          "History of Art",
          "History of Literature",
          "History of Music",
          "History of Theater",
          "History of Religion",
          "History of Science",
          "History of Philosophy",
          "History of Fashion",
          "History of Sports",
          "History of Food",
          "Folklore",
          "History of Media",
        ],
      },
      {
        name: "Political History",
        subSubGenres: [
          "Political Revolutions",
          "Political Movements",
          "History of Political Thought",
          "History of Democracy",
          "History of Socialism",
          "History of Communism",
          "History of Fascism",
          "History of Nationalism",
          "History of Liberalism",
          "Colonial History",
          "Imperialism",
        ],
      },
      {
        name: "Environmental History",
        subSubGenres: [
          "History of Climate",
          "History of Conservation",
          "History of Agriculture",
          "History of Pollution",
          "Industrial Impact",
          "Environmental Movements",
          "Natural Disasters",
          "Human-Environment Interaction",
          "History of Resource Management",
          "Eco-history",
        ],
      },
      {
        name: "Intellectual History",
        subSubGenres: [
          "History of Ideas",
          "History of Philosophy",
          "History of Science",
          "History of Religion",
          "History of Education",
          "History of Human Thought",
          "Cultural Movements",
          "Enlightenment",
          "Renaissance",
          "Scientific Revolution",
          "Intellectual Traditions",
        ],
      },
      {
        name: "Local and Regional History",
        subSubGenres: [
          "Local Histories",
          "Regional Studies",
          "Urban History",
          "Rural History",
          "Microhistory",
          "Local Communities",
          "Regional Cultures",
          "Historical Geography",
          "Heritage Studies",
          "Local Archives",
          "Local Genealogy",
          "Local Narratives",
        ],
      },
    ],
  },
];
